// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models.EfModels;

public partial class Category
{
    public int Id { get; set; }

    public string CategoryName { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}


public partial class CategoryVM
{
	public int Id { get; set; }

	[Display(Name = "分類名稱")]
	[Required(ErrorMessage ="分類名稱必填")]
	[StringLength(50)]
	public string CategoryName { get; set; }
	[Display(Name = "顯示順序")]
	[Required(ErrorMessage = "顯示名稱必填")]
	public int DisplayOrder { get; set; }
	[Display(Name = "下架")]
	public bool IsDeleted { get; set; }

	public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}