// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models.EfModels;

public partial class Order
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public DateTime OrderTime { get; set; }

    public string Status { get; set; }

    public decimal Total { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}