// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models.EfModels;

public partial class Product
{
    public int Id { get; set; }

    public int CategoryId { get; set; }

    public int SupplierId { get; set; }

    public string ProductName { get; set; }

    public decimal OrigPrice { get; set; }

    public decimal UnitPrice { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Supplier Supplier { get; set; }
}