// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models.EfModels;

public partial class Role
{
    public int id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<RoleId> RoleIds { get; set; } = new List<RoleId>();
}