// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models.EfModels;

public partial class RoleId
{
    public int id { get; set; }

    public int Userid { get; set; }

    public string RoleId1 { get; set; }

    public virtual Role User { get; set; }

    public virtual User UserNavigation { get; set; }
}