// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models.EfModels;

public partial class Supplier
{
    public int Id { get; set; }

    public string CompanyName { get; set; }

    public string TaxId { get; set; }

    public string Fax { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual SupplierContact SupplierContact { get; set; }
}