// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models.EfModels;

public partial class SupplierContactMethod
{
    public int Id { get; set; }

    public int SupplierContactId { get; set; }

    public string MethodType { get; set; }

    public string MethodValue { get; set; }

    public virtual SupplierContact SupplierContact { get; set; }
}